name: autocaption
description: Auto Caption App
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  video_player: ^2.8.2
  google_fonts: ^6.1.0
flutter:
  uses-material-design: true
